# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements
RUN pip install --no-cache-dir --user selenium webdriver-manager

# Make port 80 available to the world outside this container
EXPOSE 80

# Run server.py when the container launches
ENTRYPOINT ["python3", "src/mcp_server_selenium/server.py"]
